package cn.dandong.entity;

public class County {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column county.cid
     *
     * @mbg.generated Tue Jul 30 21:45:47 CST 2019
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column county.cname
     *
     * @mbg.generated Tue Jul 30 21:45:47 CST 2019
     */
    private String cname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column county.remark
     *
     * @mbg.generated Tue Jul 30 21:45:47 CST 2019
     */
    private String remark;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column county.cid
     *
     * @return the value of county.cid
     *
     * @mbg.generated Tue Jul 30 21:45:47 CST 2019
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column county.cid
     *
     * @param id the value for county.cid
     *
     * @mbg.generated Tue Jul 30 21:45:47 CST 2019
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column county.cname
     *
     * @return the value of county.cname
     *
     * @mbg.generated Tue Jul 30 21:45:47 CST 2019
     */
    public String getCname() {
        return cname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column county.cname
     *
     * @param cname the value for county.cname
     *
     * @mbg.generated Tue Jul 30 21:45:47 CST 2019
     */
    public void setCname(String cname) {
        this.cname = cname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column county.remark
     *
     * @return the value of county.remark
     *
     * @mbg.generated Tue Jul 30 21:45:47 CST 2019
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column county.remark
     *
     * @param remark the value for county.remark
     *
     * @mbg.generated Tue Jul 30 21:45:47 CST 2019
     */
    public void setRemark(String remark) {
        this.remark = remark;
    }
}