package cn.dandong.entity;

public class Ethnic {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ethnic.eid
     *
     * @mbg.generated Sun Aug 11 13:16:36 CST 2019
     */
    private Integer eid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ethnic.ename
     *
     * @mbg.generated Sun Aug 11 13:16:36 CST 2019
     */
    private String ename;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ethnic.remarks
     *
     * @mbg.generated Sun Aug 11 13:16:36 CST 2019
     */
    private String remarks;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ethnic.eid
     *
     * @return the value of ethnic.eid
     *
     * @mbg.generated Sun Aug 11 13:16:36 CST 2019
     */
    public Integer getEid() {
        return eid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ethnic.eid
     *
     * @param eid the value for ethnic.eid
     *
     * @mbg.generated Sun Aug 11 13:16:36 CST 2019
     */
    public void setEid(Integer eid) {
        this.eid = eid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ethnic.ename
     *
     * @return the value of ethnic.ename
     *
     * @mbg.generated Sun Aug 11 13:16:36 CST 2019
     */
    public String getEname() {
        return ename;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ethnic.ename
     *
     * @param ename the value for ethnic.ename
     *
     * @mbg.generated Sun Aug 11 13:16:36 CST 2019
     */
    public void setEname(String ename) {
        this.ename = ename;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ethnic.remarks
     *
     * @return the value of ethnic.remarks
     *
     * @mbg.generated Sun Aug 11 13:16:36 CST 2019
     */
    public String getRemarks() {
        return remarks;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ethnic.remarks
     *
     * @param remarks the value for ethnic.remarks
     *
     * @mbg.generated Sun Aug 11 13:16:36 CST 2019
     */
    public void setRemarks(String remarks) {
        this.remarks = remarks;
    }
}