package cn.dandong.entity;

public class Ethnic {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ethnic.eid
     *
     * @mbg.generated Tue Jul 30 22:25:16 CST 2019
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ethnic.ename
     *
     * @mbg.generated Tue Jul 30 22:25:16 CST 2019
     */
    private String ename;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ethnic.memo
     *
     * @mbg.generated Tue Jul 30 22:25:16 CST 2019
     */
    private String memo;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ethnic.eid
     *
     * @return the value of ethnic.eid
     *
     * @mbg.generated Tue Jul 30 22:25:16 CST 2019
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ethnic.eid
     *
     * @param id the value for ethnic.eid
     *
     * @mbg.generated Tue Jul 30 22:25:16 CST 2019
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ethnic.ename
     *
     * @return the value of ethnic.ename
     *
     * @mbg.generated Tue Jul 30 22:25:16 CST 2019
     */
    public String getEname() {
        return ename;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ethnic.ename
     *
     * @param ename the value for ethnic.ename
     *
     * @mbg.generated Tue Jul 30 22:25:16 CST 2019
     */
    public void setEname(String ename) {
        this.ename = ename;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ethnic.memo
     *
     * @return the value of ethnic.memo
     *
     * @mbg.generated Tue Jul 30 22:25:16 CST 2019
     */
    public String getMemo() {
        return memo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ethnic.memo
     *
     * @param memo the value for ethnic.memo
     *
     * @mbg.generated Tue Jul 30 22:25:16 CST 2019
     */
    public void setMemo(String memo) {
        this.memo = memo;
    }
}