package cn.dandong.entity;

public class Town {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column town.tid
     *
     * @mbg.generated Sun Aug 11 13:18:45 CST 2019
     */
    private Integer tid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column town.tname
     *
     * @mbg.generated Sun Aug 11 13:18:45 CST 2019
     */
    private String tname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column town.remark
     *
     * @mbg.generated Sun Aug 11 13:18:45 CST 2019
     */
    private String remark;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column town.cid
     *
     * @mbg.generated Sun Aug 11 13:18:45 CST 2019
     */
    private Integer county;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column town.tid
     *
     * @return the value of town.tid
     *
     * @mbg.generated Sun Aug 11 13:18:45 CST 2019
     */
    public Integer getTid() {
        return tid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column town.tid
     *
     * @param tid the value for town.tid
     *
     * @mbg.generated Sun Aug 11 13:18:45 CST 2019
     */
    public void setTid(Integer tid) {
        this.tid = tid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column town.tname
     *
     * @return the value of town.tname
     *
     * @mbg.generated Sun Aug 11 13:18:45 CST 2019
     */
    public String getTname() {
        return tname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column town.tname
     *
     * @param tname the value for town.tname
     *
     * @mbg.generated Sun Aug 11 13:18:45 CST 2019
     */
    public void setTname(String tname) {
        this.tname = tname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column town.remark
     *
     * @return the value of town.remark
     *
     * @mbg.generated Sun Aug 11 13:18:45 CST 2019
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column town.remark
     *
     * @param remark the value for town.remark
     *
     * @mbg.generated Sun Aug 11 13:18:45 CST 2019
     */
    public void setRemark(String remark) {
        this.remark = remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column town.cid
     *
     * @return the value of town.cid
     *
     * @mbg.generated Sun Aug 11 13:18:45 CST 2019
     */
    public Integer getCounty() {
        return county;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column town.cid
     *
     * @param county the value for town.cid
     *
     * @mbg.generated Sun Aug 11 13:18:45 CST 2019
     */
    public void setCounty(Integer county) {
        this.county = county;
    }
}