package cn.dandong.entity;

import java.math.BigDecimal;

public class Town {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column town.tid
     *
     * @mbg.generated Tue Jul 30 22:28:38 CST 2019
     */
    private Integer tid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column town.tname
     *
     * @mbg.generated Tue Jul 30 22:28:38 CST 2019
     */
    private String tname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column town.people
     *
     * @mbg.generated Tue Jul 30 22:28:38 CST 2019
     */
    private Integer people;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column town.groupcount
     *
     * @mbg.generated Tue Jul 30 22:28:38 CST 2019
     */
    private Integer groupcount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column town.totalarea
     *
     * @mbg.generated Tue Jul 30 22:28:38 CST 2019
     */
    private BigDecimal totalarea;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column town.landarea
     *
     * @mbg.generated Tue Jul 30 22:28:38 CST 2019
     */
    private BigDecimal landarea;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column town.waterarea
     *
     * @mbg.generated Tue Jul 30 22:28:38 CST 2019
     */
    private BigDecimal waterarea;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column town.cid
     *
     * @mbg.generated Tue Jul 30 22:28:38 CST 2019
     */
    private County county;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column town.tid
     *
     * @return the value of town.tid
     *
     * @mbg.generated Tue Jul 30 22:28:38 CST 2019
     */
    public Integer getTid() {
        return tid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column town.tid
     *
     * @param tid the value for town.tid
     *
     * @mbg.generated Tue Jul 30 22:28:38 CST 2019
     */
    public void setTid(Integer tid) {
        this.tid = tid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column town.tname
     *
     * @return the value of town.tname
     *
     * @mbg.generated Tue Jul 30 22:28:38 CST 2019
     */
    public String getTname() {
        return tname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column town.tname
     *
     * @param tname the value for town.tname
     *
     * @mbg.generated Tue Jul 30 22:28:38 CST 2019
     */
    public void setTname(String tname) {
        this.tname = tname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column town.people
     *
     * @return the value of town.people
     *
     * @mbg.generated Tue Jul 30 22:28:38 CST 2019
     */
    public Integer getPeople() {
        return people;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column town.people
     *
     * @param people the value for town.people
     *
     * @mbg.generated Tue Jul 30 22:28:38 CST 2019
     */
    public void setPeople(Integer people) {
        this.people = people;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column town.groupcount
     *
     * @return the value of town.groupcount
     *
     * @mbg.generated Tue Jul 30 22:28:38 CST 2019
     */
    public Integer getGroupcount() {
        return groupcount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column town.groupcount
     *
     * @param groupcount the value for town.groupcount
     *
     * @mbg.generated Tue Jul 30 22:28:38 CST 2019
     */
    public void setGroupcount(Integer groupcount) {
        this.groupcount = groupcount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column town.totalarea
     *
     * @return the value of town.totalarea
     *
     * @mbg.generated Tue Jul 30 22:28:38 CST 2019
     */
    public BigDecimal getTotalarea() {
        return totalarea;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column town.totalarea
     *
     * @param totalarea the value for town.totalarea
     *
     * @mbg.generated Tue Jul 30 22:28:38 CST 2019
     */
    public void setTotalarea(BigDecimal totalarea) {
        this.totalarea = totalarea;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column town.landarea
     *
     * @return the value of town.landarea
     *
     * @mbg.generated Tue Jul 30 22:28:38 CST 2019
     */
    public BigDecimal getLandarea() {
        return landarea;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column town.landarea
     *
     * @param landarea the value for town.landarea
     *
     * @mbg.generated Tue Jul 30 22:28:38 CST 2019
     */
    public void setLandarea(BigDecimal landarea) {
        this.landarea = landarea;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column town.waterarea
     *
     * @return the value of town.waterarea
     *
     * @mbg.generated Tue Jul 30 22:28:38 CST 2019
     */
    public BigDecimal getWaterarea() {
        return waterarea;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column town.waterarea
     *
     * @param waterarea the value for town.waterarea
     *
     * @mbg.generated Tue Jul 30 22:28:38 CST 2019
     */
    public void setWaterarea(BigDecimal waterarea) {
        this.waterarea = waterarea;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column town.cid
     *
     * @return the value of town.cid
     *
     * @mbg.generated Tue Jul 30 22:28:38 CST 2019
     */
    public County getCounty() {
        return county;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column town.cid
     *
     * @param county the value for town.cid
     *
     * @mbg.generated Tue Jul 30 22:28:38 CST 2019
     */
    public void setCounty(County county) {
        this.county = county;
    }
}