package cn.dandong.entity;

import java.math.BigDecimal;

public class Villagebasicinfo {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column villagebasicinfo.vid
     *
     * @mbg.generated Tue Jul 30 22:36:06 CST 2019
     */
    private Integer vid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column villagebasicinfo.vname
     *
     * @mbg.generated Tue Jul 30 22:36:06 CST 2019
     */
    private String vname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column villagebasicinfo.people
     *
     * @mbg.generated Tue Jul 30 22:36:06 CST 2019
     */
    private Integer people;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column villagebasicinfo.groupcount
     *
     * @mbg.generated Tue Jul 30 22:36:06 CST 2019
     */
    private Integer groupcount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column villagebasicinfo.totalarea
     *
     * @mbg.generated Tue Jul 30 22:36:06 CST 2019
     */
    private BigDecimal totalarea;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column villagebasicinfo.landarea
     *
     * @mbg.generated Tue Jul 30 22:36:06 CST 2019
     */
    private BigDecimal landarea;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column villagebasicinfo.waterarea
     *
     * @mbg.generated Tue Jul 30 22:36:06 CST 2019
     */
    private BigDecimal waterarea;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column villagebasicinfo.tid
     *
     * @mbg.generated Tue Jul 30 22:36:06 CST 2019
     */
    private Town town;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column villagebasicinfo.vid
     *
     * @return the value of villagebasicinfo.vid
     *
     * @mbg.generated Tue Jul 30 22:36:06 CST 2019
     */
    public Integer getVid() {
        return vid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column villagebasicinfo.vid
     *
     * @param vid the value for villagebasicinfo.vid
     *
     * @mbg.generated Tue Jul 30 22:36:06 CST 2019
     */
    public void setVid(Integer vid) {
        this.vid = vid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column villagebasicinfo.vname
     *
     * @return the value of villagebasicinfo.vname
     *
     * @mbg.generated Tue Jul 30 22:36:06 CST 2019
     */
    public String getVname() {
        return vname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column villagebasicinfo.vname
     *
     * @param vname the value for villagebasicinfo.vname
     *
     * @mbg.generated Tue Jul 30 22:36:06 CST 2019
     */
    public void setVname(String vname) {
        this.vname = vname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column villagebasicinfo.people
     *
     * @return the value of villagebasicinfo.people
     *
     * @mbg.generated Tue Jul 30 22:36:06 CST 2019
     */
    public Integer getPeople() {
        return people;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column villagebasicinfo.people
     *
     * @param people the value for villagebasicinfo.people
     *
     * @mbg.generated Tue Jul 30 22:36:06 CST 2019
     */
    public void setPeople(Integer people) {
        this.people = people;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column villagebasicinfo.groupcount
     *
     * @return the value of villagebasicinfo.groupcount
     *
     * @mbg.generated Tue Jul 30 22:36:06 CST 2019
     */
    public Integer getGroupcount() {
        return groupcount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column villagebasicinfo.groupcount
     *
     * @param groupcount the value for villagebasicinfo.groupcount
     *
     * @mbg.generated Tue Jul 30 22:36:06 CST 2019
     */
    public void setGroupcount(Integer groupcount) {
        this.groupcount = groupcount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column villagebasicinfo.totalarea
     *
     * @return the value of villagebasicinfo.totalarea
     *
     * @mbg.generated Tue Jul 30 22:36:06 CST 2019
     */
    public BigDecimal getTotalarea() {
        return totalarea;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column villagebasicinfo.totalarea
     *
     * @param totalarea the value for villagebasicinfo.totalarea
     *
     * @mbg.generated Tue Jul 30 22:36:06 CST 2019
     */
    public void setTotalarea(BigDecimal totalarea) {
        this.totalarea = totalarea;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column villagebasicinfo.landarea
     *
     * @return the value of villagebasicinfo.landarea
     *
     * @mbg.generated Tue Jul 30 22:36:06 CST 2019
     */
    public BigDecimal getLandarea() {
        return landarea;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column villagebasicinfo.landarea
     *
     * @param landarea the value for villagebasicinfo.landarea
     *
     * @mbg.generated Tue Jul 30 22:36:06 CST 2019
     */
    public void setLandarea(BigDecimal landarea) {
        this.landarea = landarea;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column villagebasicinfo.waterarea
     *
     * @return the value of villagebasicinfo.waterarea
     *
     * @mbg.generated Tue Jul 30 22:36:06 CST 2019
     */
    public BigDecimal getWaterarea() {
        return waterarea;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column villagebasicinfo.waterarea
     *
     * @param waterarea the value for villagebasicinfo.waterarea
     *
     * @mbg.generated Tue Jul 30 22:36:06 CST 2019
     */
    public void setWaterarea(BigDecimal waterarea) {
        this.waterarea = waterarea;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column villagebasicinfo.tid
     *
     * @return the value of villagebasicinfo.tid
     *
     * @mbg.generated Tue Jul 30 22:36:06 CST 2019
     */
    public Town getTown() {
        return town;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column villagebasicinfo.tid
     *
     * @param town the value for villagebasicinfo.tid
     *
     * @mbg.generated Tue Jul 30 22:36:06 CST 2019
     */
    public void setTown(Town town) {
        this.town = town;
    }
}