package cn.dandong.entity;

public class Villageethnic1 {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column villageethnic1.id
	 * @mbg.generated  Tue Jul 30 22:44:25 CST 2019
	 */
	private Integer id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column villageethnic1.vid
	 * @mbg.generated  Tue Jul 30 22:44:25 CST 2019
	 */
	private Villagebasicinfo villagebasicinfo;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column villageethnic1.eid
	 * @mbg.generated  Tue Jul 30 22:44:25 CST 2019
	 */
	private Ethnic ethnic;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column villageethnic1.id
	 * @return  the value of villageethnic1.id
	 * @mbg.generated  Tue Jul 30 22:44:25 CST 2019
	 */
	public Integer getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column villageethnic1.id
	 * @param id  the value for villageethnic1.id
	 * @mbg.generated  Tue Jul 30 22:44:25 CST 2019
	 */
	public void setId(Integer id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column villageethnic1.vid
	 * @return  the value of villageethnic1.vid
	 * @mbg.generated  Tue Jul 30 22:44:25 CST 2019
	 */
	public Villagebasicinfo getVillagebasicinfo() {
		return villagebasicinfo;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column villageethnic1.vid
	 * @param villagebasicinfo  the value for villageethnic1.vid
	 * @mbg.generated  Tue Jul 30 22:44:25 CST 2019
	 */
	public void setVillagebasicinfo(Villagebasicinfo villagebasicinfo) {
		this.villagebasicinfo = villagebasicinfo;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column villageethnic1.eid
	 * @return  the value of villageethnic1.eid
	 * @mbg.generated  Tue Jul 30 22:44:25 CST 2019
	 */
	public Ethnic getEthnic() {
		return ethnic;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column villageethnic1.eid
	 * @param ethnic  the value for villageethnic1.eid
	 * @mbg.generated  Tue Jul 30 22:44:25 CST 2019
	 */
	public void setEthnic(Ethnic ethnic) {
		this.ethnic = ethnic;
	}
}