package cn.dandong.service;

import java.util.List;

import cn.dandong.entity.Town;

public interface TownService {
	/**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table town
     *
     * @mbg.generated Tue Jul 30 22:28:38 CST 2019
     */
    int deleteByPrimaryKey(Integer tid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table town
     *
     * @mbg.generated Tue Jul 30 22:28:38 CST 2019
     */
    int insert(Town record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table town
     *
     * @mbg.generated Tue Jul 30 22:28:38 CST 2019
     */
    Town selectByPrimaryKey(Integer tid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table town
     *
     * @mbg.generated Tue Jul 30 22:28:38 CST 2019
     */
    List<Town> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table town
     *
     * @mbg.generated Tue Jul 30 22:28:38 CST 2019
     */
    int updateByPrimaryKey(Town record);
}