package cn.dandong.service;

import java.util.List;

import cn.dandong.entity.Villagebasicinfo;
import cn.dandong.entity.Villageethnic;

public interface VillageethnicService {
	 /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table villageethnic
     *
     * @mbg.generated Tue Jul 30 23:13:35 CST 2019
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table villageethnic
     *
     * @mbg.generated Tue Jul 30 23:13:35 CST 2019
     */
    int insert(Villageethnic record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table villageethnic
     *
     * @mbg.generated Tue Jul 30 23:13:35 CST 2019
     */
    Villageethnic selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table villageethnic
     *
     * @mbg.generated Tue Jul 30 23:13:35 CST 2019
     */
    List<Villageethnic> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table villageethnic
     *
     * @mbg.generated Tue Jul 30 23:13:35 CST 2019
     */
    int updateByPrimaryKey(Villageethnic record);
}