package cn.dandong.service;

import java.util.List;

import cn.dandong.entity.Villageethnic1;

public interface Villageethnic1Service {
	/**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table villageethnic1
     *
     * @mbg.generated Tue Jul 30 22:44:25 CST 2019
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table villageethnic1
     *
     * @mbg.generated Tue Jul 30 22:44:25 CST 2019
     */
    int insert(Villageethnic1 record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table villageethnic1
     *
     * @mbg.generated Tue Jul 30 22:44:25 CST 2019
     */
    Villageethnic1 selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table villageethnic1
     *
     * @mbg.generated Tue Jul 30 22:44:25 CST 2019
     */
    List<Villageethnic1> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table villageethnic1
     *
     * @mbg.generated Tue Jul 30 22:44:25 CST 2019
     */
    int updateByPrimaryKey(Villageethnic1 record);
}