package cn.dandong.service;

import java.util.List;

import cn.dandong.entity.Villagebasicinfo;

public interface VillagebasicinfoService {
	/**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table villagebasicinfo
     *
     * @mbg.generated Tue Jul 30 22:36:06 CST 2019
     */
    int deleteByPrimaryKey(Integer vid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table villagebasicinfo
     *
     * @mbg.generated Tue Jul 30 22:36:06 CST 2019
     */
    int insert(Villagebasicinfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table villagebasicinfo
     *
     * @mbg.generated Tue Jul 30 22:36:06 CST 2019
     */
    Villagebasicinfo selectByPrimaryKey(Integer vid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table villagebasicinfo
     *
     * @mbg.generated Tue Jul 30 22:36:06 CST 2019
     */
    List<Villagebasicinfo> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table villagebasicinfo
     *
     * @mbg.generated Tue Jul 30 22:36:06 CST 2019
     */
    int updateByPrimaryKey(Villagebasicinfo record);
}