package cn.dandong.mapper;

import cn.dandong.entity.County;
import java.util.List;

public interface CountyMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table county
     *
     * @mbg.generated Sun Aug 11 13:16:04 CST 2019
     */
    int deleteByPrimaryKey(Integer cid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table county
     *
     * @mbg.generated Sun Aug 11 13:16:04 CST 2019
     */
    int insert(County record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table county
     *
     * @mbg.generated Sun Aug 11 13:16:04 CST 2019
     */
    County selectByPrimaryKey(Integer cid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table county
     *
     * @mbg.generated Sun Aug 11 13:16:04 CST 2019
     */
    List<County> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table county
     *
     * @mbg.generated Sun Aug 11 13:16:04 CST 2019
     */
    int updateByPrimaryKey(County record);
    
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table county
     *
     * @mbg.generated Sun Aug 11 13:16:04 CST 2019
     */
    int countCounty();
    
    
}