package cn.dandong.mapper;

import cn.dandong.entity.Ethnic;
import java.util.List;

public interface EthnicMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ethnic
     *
     * @mbg.generated Tue Jul 30 22:25:16 CST 2019
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ethnic
     *
     * @mbg.generated Tue Jul 30 22:25:16 CST 2019
     */
    int insert(Ethnic record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ethnic
     *
     * @mbg.generated Tue Jul 30 22:25:16 CST 2019
     */
    Ethnic selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ethnic
     *
     * @mbg.generated Tue Jul 30 22:25:16 CST 2019
     */
    List<Ethnic> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ethnic
     *
     * @mbg.generated Tue Jul 30 22:25:16 CST 2019
     */
    int updateByPrimaryKey(Ethnic record);
}