package cn.dandong.mapper;

import cn.dandong.entity.Ethnic;
import java.util.List;

public interface EthnicMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ethnic
     *
     * @mbg.generated Sun Aug 11 13:16:36 CST 2019
     */
    int deleteByPrimaryKey(Integer eid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ethnic
     *
     * @mbg.generated Sun Aug 11 13:16:36 CST 2019
     */
    int insert(Ethnic record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ethnic
     *
     * @mbg.generated Sun Aug 11 13:16:36 CST 2019
     */
    Ethnic selectByPrimaryKey(Integer eid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ethnic
     *
     * @mbg.generated Sun Aug 11 13:16:36 CST 2019
     */
    List<Ethnic> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ethnic
     *
     * @mbg.generated Sun Aug 11 13:16:36 CST 2019
     */
    int updateByPrimaryKey(Ethnic record);
}