package cn.dandong.mapper;

import cn.dandong.entity.Town;
import java.util.List;

public interface TownMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table town
     *
     * @mbg.generated Tue Jul 30 22:28:38 CST 2019
     */
    int deleteByPrimaryKey(Integer tid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table town
     *
     * @mbg.generated Tue Jul 30 22:28:38 CST 2019
     */
    int insert(Town record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table town
     *
     * @mbg.generated Tue Jul 30 22:28:38 CST 2019
     */
    Town selectByPrimaryKey(Integer tid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table town
     *
     * @mbg.generated Tue Jul 30 22:28:38 CST 2019
     */
    List<Town> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table town
     *
     * @mbg.generated Tue Jul 30 22:28:38 CST 2019
     */
    int updateByPrimaryKey(Town record);
}