package cn.dandong.mapper;

import cn.dandong.entity.Villageethnic1;
import java.util.List;

public interface Villageethnic1Mapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table villageethnic1
     *
     * @mbg.generated Tue Jul 30 22:44:25 CST 2019
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table villageethnic1
     *
     * @mbg.generated Tue Jul 30 22:44:25 CST 2019
     */
    int insert(Villageethnic1 record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table villageethnic1
     *
     * @mbg.generated Tue Jul 30 22:44:25 CST 2019
     */
    Villageethnic1 selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table villageethnic1
     *
     * @mbg.generated Tue Jul 30 22:44:25 CST 2019
     */
    List<Villageethnic1> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table villageethnic1
     *
     * @mbg.generated Tue Jul 30 22:44:25 CST 2019
     */
    int updateByPrimaryKey(Villageethnic1 record);
}